const CONSTANT = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    FETCH_ACCOUNT_DETAIL_REQUEST: 'FETCH_ACCOUNT_DETAIL_REQUEST',
    FETCH_ACCOUNT_DETAIL_SUCCESS: 'FETCH_ACCOUNT_DETAIL_SUCCESS',
    FETCH_ACCOUNT_DETAIL_FAILURE: 'FETCH_ACCOUNT_DETAIL_FAILURE',

    FETCH_ADDRESS_REQUEST: 'FETCH_ADDRESS_REQUEST',
    FETCH_ADDRESS_SUCCESS: 'FETCH_ADDRESS_SUCCESS',
    FETCH_ADDRESS_FAILURE: 'FETCH_ADDRESS_FAILURE',

    FETCH_BANNER_REQUEST: 'FETCH_BANNER_REQUEST',
    FETCH_BANNER_SUCCESS: 'FETCH_BANNER_SUCCESS',
    FETCH_BANNER_FAILURE: 'FETCH_BANNER_FAILURE',

    FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE',

    FETCH_CATALOG_REQUEST: 'FETCH_CATALOG_REQUEST',
    FETCH_CATALOG_SUCCESS: 'FETCH_CATALOG_SUCCESS',
    FETCH_CATALOG_FAILURE: 'FETCH_CATALOG_FAILURE',

    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE: 'FETCH_PRODUCT_FAILURE',

    FETCH_ORDER_REQUEST: 'FETCH_ORDER_REQUEST',
    FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_FAILURE: 'FETCH_ORDER_FAILURE',

    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE: 'CREATE_ORDER_FAILURE',

    ADD_ITEM_TO_CART_REQUEST: 'ADD_ITEM_TO_CART_REQUEST',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    ADD_ITEM_TO_CART_FAILURE: 'ADD_ITEM_TO_CART_FAILURE',

    UPDATE_CART_ITEM_REQUEST: 'UPDATE_CART_ITEM_REQUEST',
    UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
    UPDATE_CART_ITEM_FAILURE: 'UPDATE_CART_ITEM_FAILURE',

    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    DELETE_CART_ITEM_REQUEST: 'DELETE_CART_ITEM_REQUEST',
    DELETE_CART_ITEM_SUCCESS: 'DELETE_CART_ITEM_SUCCESS',

    FETCH_SHIPMENT_COST_REQUEST: 'FETCH_SHIPMENT_COST_REQUEST',
    FETCH_SHIPMENT_COST_SUCCESS: 'FETCH_SHIPMENT_COST_SUCCESS',
    FETCH_SHIPMENT_COST_FAILURE: 'FETCH_SHIPMENT_COST_FAILURE',

    FETCH_REFERRAL_DOWNLINE_REQUEST: 'FETCH_REFERRAL_DOWNLINE_REQUEST',
    FETCH_REFERRAL_DOWNLINE_SUCCESS: 'FETCH_REFERRAL_DOWNLINE_SUCCESS',
    FETCH_REFERRAL_DOWNLINE_FAILURE: 'FETCH_REFERRAL_DOWNLINE_FAILURE',

    FETCH_REFERRAL_INCOME_REQUEST: 'FETCH_REFERRAL_INCOME_REQUEST',
    FETCH_REFERRAL_INCOME_SUCCESS: 'FETCH_REFERRAL_INCOME_SUCCESS',
    FETCH_REFERRAL_INCOME_FAILURE: 'FETCH_REFERRAL_INCOME_FAILURE',

    SET_FULLSCREEN_LOADER: 'SET_FULLSCREEN_LOADER',
    SET_SEARCH_DIALOG: 'SET_SEARCH_DIALOG',
    SET_TOAST_MESSAGE: 'SET_TOAST_MESSAGE'
};

export default CONSTANT;
